servers:
  - host: 10.109.118.180
    port: 22
    username: wxf
    password: xiaoxiao0103
  - host: 10.109.119.118
    port: 22
    username: wangxianfeng
    password: feng0103
  - host: 10.109.118.186
    port: 22
    username: wxf
    password: fengfeng0627