/*
Copyright © 2025 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"

	"github.com/spf13/cobra"
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "tools",
	Short: "some tools",
	Long:  `some tools`,
	// Uncomment the following line if your bare application
	// has an action associated with it:
	// Run: func(cmd *cobra.Command, args []string) { },
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func init() {
	// Here you will define your flags and configuration settings.
	// Cobra supports persistent flags, which, if defined here,
	// will be global for your application.

	// rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.tools.yaml)")

	// Cobra also supports local flags, which will only run
	// when this action is called directly.
	rootCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")

	// 初始化配置文件
	cobra.OnInitialize(initConfig)
}

// initConfig 初始化配置文件，如果不存在则创建
func initConfig() {
	usr, err := user.Current()
	if err != nil {
		return
	}

	configDir := filepath.Join(usr.HomeDir, ".tools")
	configPath := filepath.Join(configDir, "config.yaml")

	// 检查配置文件是否存在
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		// 创建配置目录
		if err := os.MkdirAll(configDir, 0755); err != nil {
			return
		}

		// 创建默认配置文件
		defaultConfig := `# Tools Configuration File
# Generated by tools CLI

# FX Server Configuration
# Used by 'tools fx' command for file upload/download
fx_server:
  server: "http://localhost:8080"  # Your fx_server URL

# Add more configurations as needed
`

		if err := os.WriteFile(configPath, []byte(defaultConfig), 0644); err != nil {
			return
		}

		fmt.Printf("✓ Created config file: %s\n", configPath)
	}
}
